version: '3.8'

services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn fundme.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/fundme/
    ports:
      - 8000:8000
    env_file:
      - ./fundme/.env
    depends_on:
      - db
    networks:
      - db-net
  web:
    restart: always
    build:
      context: ./fundme/frontend/
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - db-net
  webserver:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./fundme/.env
    networks:
      - db-net
volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge
