version: '3.8'

services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn fundme.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/fundme/
    ports:
      - 8000:8000
    env_file:
      - ./fundme/.env
    depends_on:
      - db
    networks:
      - db-net
  web:
    restart: always
    build:
      context: ./fundme/frontend/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./fundme/frontend:/usr/src/fundme/fundme/frontend
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - api
    networks:
      - db-net
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./fundme/.env
    networks:
      - db-net
volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge
